### ISSUE TITLE
Particles issue

### ISSUE THREAD

**Issue by ipankajkumar93** [salihkilicli/salihkilicli.github.io#1]
I followed the steps of including particles.js in my blog as well, but I noticed that once you resize the browser (Example: mobile device, ipad etc), then in portrait mode the particles only move in the top half.

Solution : Instead of inserting a new div inside background image div, just assign the id "particles-js" to that background div itself.
that way the canvas will be formed inside the background image div instead of a new div below that which doesn't follow the width and height of background.

Old code

```
<div
    class="background container-fluid" 
    style="background-image: url('{{ strings.TrimSuffix "/" site.BaseURL }}{{ $backgroundImage | relURL }}');"
  >
  <div id="particles-js"></div>
  </div>
```

New code

```
<div
    class="background container-fluid" id="particles-js"
    style="background-image: url('{{ strings.TrimSuffix "/" site.BaseURL }}{{ $backgroundImage | relURL }}');"
  >
  </div>
```

**Comment by salihkilicli** [comment]
Thank you, I realized that after you mentioned. However, when I tried the change you suggested, it completely removed the `particles` effect from my main page.

I will look into that problem when I have time. I appreciated it.

**Comment by ipankajkumar93** [comment]
> Thank you, I realized that after you mentioned. However, when I tried the change you suggested, it completely removed the `particles` effect from my main page.
> 
> I will look into that problem when I have time. I appreciated it.

That's weird.
We both have the same source code and I copied the particles.js instructions from your description itself.
It works like a charm on my blog www.ipankajsingh.com , even in mobile mode.

**Comment by salihkilicli** [comment]
Hi, sorry for the late reply. I got what you mean now and fixed the issue. Appreciated it!
